require('./User');
// require('./posts');
// require('./postComments');
// require('./postCategories');
// require('./galleries');
require('./Enquiry');
// require('./everything');
require('./homepage');
require('./navbar');
require('./menu');
require('./footer');
require('./companyprofile');
require('./companyinfolistmenu');
require('./mangementteam');
require('./differentiator');
require('./career');
require('./partner');
require('./softwareproduct');
require('./listingmenu');
require('./consultingservice');
require('./msp');
require('./specializedanalyse');
require('./offering');
require('./technologyresale');
require('./analyticalportal');
require('./tibcospotfire');
require('./tibcospotfirecustom');
require('./marketresearch');
require('./readmore');
require('./healthcareinsurer');
require('./healthcareprovider');
require('./employer');
require('./pharmaceutical');
require('./researchinstitute');
require('./lifestyleindustry');
require('./crm');
require('./lawenforcement');
require('./datawarehouse');
require('./visualbusinessintelligence');
require('./predictivemodeling');
require('./businessprocessstrategy');
require('./comparativebenchmarking');
require('./ecommerceportal');
require('./geospatialanalytic');
require('./informationreportingstrategy');
require('./socialmediaanalyse');
require('./footermenunavigation');
require('./allnewes');
require('./news1');
require('./news2');
require('./news3');
require('./news4');
require('./whatweoffersnavigation');

